language: rust
sudo: required
dist: trusty

os:
  - linux
  - osx

rust:
  - stable
  - nightly

before_install: |
  case $TRAVIS_OS_NAME in
      osx)
          brew update
          brew install libsodium
          ;;
      linux)
          apt-get install -y pkg-config
          git clone https://github.com/jedisct1/libsodium --branch stable
          pushd libsodium
          ./configure
          make && make check
          sudo make install
          sudo ldconfig
          popd
          ;;
  esac

script: |
  cargo=`which cargo`
  sudo $cargo test --features="travis-ci"

