chain_indent = "Visual"
chain_one_line_max = 80
condense_wildcard_suffixes = true
fn_args_density = "Compressed"
fn_args_layout = "Visual"
fn_call_style = "Visual"
fn_call_width = 120
hard_tabs = false
max_width = 120
normalize_comments = true
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
use_try_shorthand = true
write_mode = "Overwrite"
